version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: wget -qO- --retry-connrefused https://storage.googleapis.com/matlabimagesus/public/install.sh | sudo -E bash
      - run: matlab -batch "runAllTests"
      - store_test_results:
          path: artifacts
      - store_artifacts:
          path: artifacts/junit
      - run: bash <(curl -s https://codecov.io/bash) -f artifacts/coverage/codeCoverage.xml